import type { FishSpecies, ScenarioId } from "../types/game";

export const GAME_CONFIG = {
  initialBalance: 10000,
  defaultBet: 100,
  betOptions: [10, 20, 50, 100],
  maxZones: 100,
  metersPerZone: 100,
  eventTriggerRate: 0.25,
  zoneHeight: 118,
  hookTopPercent: 42,
  visibleZoneCount: 4,
  maxVisibleFish: 8,
  maxVisibleHighFish: 2,
  maxRenderedFishPerZone: 4,
  maxRenderedFishTotal: 14,
  milestoneDepths: [2500, 5000, 7500, 10000],
  rtpModel: {
    source: "Go Deep Get Bigger RTP PDFs",
    targetTotalRtp: 0.9723,
    normalCategoryRate: 0.9,
    highCategoryRate: 0.1,
    normalFishPerZone: 3,
    highFishPerZone: 1,
    eventSpawnPerZone: 0.25,
    baseEventTriggerPerZone: 0.0625,
    extraBetEventTriggerPerZone: 0.25,
  },
  demoResultThresholds: {
    big: 2,
    mega: 5,
    super: 10,
    ultra: 20,
    ultimate: 50,
  },
  eventSpawnChances: [{ from: 1, to: 100, chance: 0.25 }],
  eventTypeWeights: [
    { type: "twin", weight: 32 },
    { type: "pearl", weight: 32 },
    { type: "puffer", weight: 12 },
    { type: "thunder", weight: 24 },
  ],
  eventRangeWeights: [
    { range: 1, weight: 22 },
    { range: 3, weight: 62 },
    { range: 5, weight: 16 },
  ],
  fishDensityBands: [
    { from: 1, to: 15, minFish: 1, maxFish: 2, lowWeight: 92, highWeight: 8 },
    { from: 16, to: 35, minFish: 1, maxFish: 3, lowWeight: 80, highWeight: 20 },
    { from: 36, to: 60, minFish: 1, maxFish: 3, lowWeight: 65, highWeight: 35 },
    { from: 61, to: 80, minFish: 2, maxFish: 3, lowWeight: 50, highWeight: 50 },
    { from: 81, to: 100, minFish: 2, maxFish: 4, lowWeight: 35, highWeight: 65 },
  ],
  buyFree: {
    enabled: true,
    costMultiplier: 100,
    showcaseSeedOffset: 701,
  },
  extraBet: {
    enabled: true,
    costMultiplier: 3,
    eventTriggerRate: 1,
  },
  eventTargetSelector: "visible-window",
  eventRanges: [1, 3, 5],
  thunderDurationWeights: [
    { duration: 2, weight: 62 },
    { duration: 3, weight: 28 },
    { duration: 4, weight: 10 },
  ],
  thunderDurations: [2, 3, 4],
  thunderReach: [3, 4],
  thunderReachWeights: [
    { reach: 3, weight: 62 },
    { reach: 4, weight: 38 },
  ],
  thunderGuaranteedRate: 0.55,
};

export const FISH_SPECIES: FishSpecies[] = [
  { id: "small-school", name: "Small School", tier: "low", multiplier: 0.1, catchRate: 0.25, color: "#78d4ff", spawnWeight: 21 },
  { id: "jelly", name: "Jellyfish", tier: "low", multiplier: 0.2, catchRate: 0.25, color: "#b58cff", spawnWeight: 18 },
  { id: "turtle", name: "Sea Turtle", tier: "low", multiplier: 0.5, catchRate: 0.25, color: "#64d38a", spawnWeight: 18 },
  { id: "red-fish", name: "Red Fish", tier: "low", multiplier: 0.8, catchRate: 0.25, color: "#ff6f75", spawnWeight: 15 },
  { id: "shark", name: "Shark", tier: "low", multiplier: 1, catchRate: 0.25, color: "#9db6c7", spawnWeight: 20 },
  { id: "red-fish-2x", name: "Red Fish", tier: "low", multiplier: 2, catchRate: 0.25, color: "#ff837d", spawnWeight: 5 },
  { id: "shark-3x", name: "Shark", tier: "low", multiplier: 3, catchRate: 0.25, color: "#b9d0df", spawnWeight: 3 },
  { id: "xuanwu", name: "Xuanwu Turtle", tier: "high", multiplier: 5, catchRate: 0.25, color: "#f0d274", spawnWeight: 50.5 },
  { id: "white-tiger", name: "White Tiger", tier: "high", multiplier: 10, catchRate: 0.25, color: "#fff3c5", spawnWeight: 30 },
  { id: "vermilion-15x", name: "Vermilion Bird", tier: "high", multiplier: 15, catchRate: 0.25, color: "#ffbd57", spawnWeight: 0.5 },
  { id: "vermilion", name: "Vermilion Bird", tier: "high", multiplier: 20, catchRate: 0.25, color: "#ff9b3d", spawnWeight: 10 },
  { id: "white-tiger-30x", name: "White Tiger", tier: "high", multiplier: 30, catchRate: 0.25, color: "#fff8d8", spawnWeight: 5 },
  { id: "xuanwu-40x", name: "Xuanwu Turtle", tier: "high", multiplier: 40, catchRate: 0.25, color: "#ffe68f", spawnWeight: 0.5 },
  { id: "azure-dragon", name: "Azure Dragon", tier: "high", multiplier: 50, catchRate: 0.25, color: "#60fff2", spawnWeight: 2 },
  { id: "azure-dragon-80x", name: "Azure Dragon", tier: "high", multiplier: 80, catchRate: 0.25, color: "#95fff7", spawnWeight: 0.5 },
  { id: "azure-dragon-100x", name: "Azure Dragon", tier: "high", multiplier: 100, catchRate: 0.25, color: "#d4fff9", spawnWeight: 1 },
  { id: "twin-fish", name: "Twin Fish", tier: "tool", multiplier: 0, catchRate: 0, color: "#8dfbff", eventType: "twin" },
  { id: "golden-pearl", name: "Golden Pearl", tier: "tool", multiplier: 0, catchRate: 0, color: "#ffd45d", eventType: "pearl" },
  { id: "puffer-bomb", name: "Puffer Bomb", tier: "tool", multiplier: 0, catchRate: 0, color: "#ffb36b", eventType: "puffer" },
  { id: "thunder-jelly", name: "Thunder Jellyfish", tier: "tool", multiplier: 0, catchRate: 0, color: "#b8f7ff", eventType: "thunder" },
];

export const SCENARIOS: Array<{ id: ScenarioId; label: string; seed: number }> = [
  { id: "random", label: "Random Run", seed: 83621 },
  { id: "normal", label: "Normal Demo", seed: 17001 },
  { id: "event-chain", label: "Event Chain Demo", seed: 33007 },
  { id: "big-win", label: "Big Win Demo", seed: 99091 },
  { id: "route-school", label: "Route Demo - School", seed: 25025 },
  { id: "route-golden", label: "Route Demo - Golden", seed: 50050 },
  { id: "route-storm", label: "Route Demo - Storm", seed: 75075 },
];
